version: "3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      - EULA=TRUE
      - TYPE=VANILLA
      - TZ=Asia/Tokyo
      - VERSION=1.15.2
      - DIFFICULTY=hard

    tty: true
    stdin_open: true
    # restart: always

    # debug command
    # entrypoint: "/bin/sh -c 'tail -f /dev/null'"
    # command: "tail -f /dev/null"

  # overviewer
  web:
    image: nginx
    volumes:
     - ./html:/usr/share/nginx/html
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
